-- Clear data generated by scripts/seed-review-demo-data.sql.
-- This removes review demo rows and resets identity sequences to start from 1.
--
-- Run before scripts/seed-review-demo-data.sql when rebuilding demo data from scratch.

begin;

truncate table
    reviews,
    reports,
    patent_annuities,
    patent_legal_status
restart identity;

commit;

