-- Generated from /Users/jungh150/Downloads/patents_keywords.csv
-- Updates patents.keywords by patents.id.
-- Run this whole file in DataGrip or psql.

begin;

with patent_keyword_updates(id, keywords) as (
    values
        (1, $patent_keywords_1$["호텔 고객관리", "숙박 관리", "체크인·체크아웃", "사인패드 결제", "청구서 보관"]$patent_keywords_1$::jsonb),
        (2, $patent_keywords_2$["간접 광고", "의류 비즈니스", "3D 아바타", "신체 정보", "착용 적합성"]$patent_keywords_2$::jsonb),
        (3, $patent_keywords_3$["모바일 패션 앨범", "사용자 제작 콘텐츠", "아바타 영상", "패션 아이템", "이동통신 단말"]$patent_keywords_3$::jsonb),
        (4, $patent_keywords_4$["온라인 본인확인", "실명 인증", "개인정보 기반 인증", "회원가입 인증", "인증 서버"]$patent_keywords_4$::jsonb),
        (5, $patent_keywords_5$["아바타 패션자문", "패션 코디네이션", "이동통신 단말", "패션 아이템", "실시간 자문"]$patent_keywords_5$::jsonb),
        (6, $patent_keywords_6$["아바타 카드전송", "3차원 스캔", "메시지 카드", "이동통신망", "개인화 카드"]$patent_keywords_6$::jsonb),
        (7, $patent_keywords_7$["전자상거래", "아바타 결제", "카드 인증", "인증 서버", "전자결제 보안"]$patent_keywords_7$::jsonb),
        (8, $patent_keywords_8$["인터넷 쇼핑몰", "아바타 인증", "회원가입 로그인", "개인정보 보호", "인증 서버"]$patent_keywords_8$::jsonb),
        (9, $patent_keywords_9$["3차원 아바타", "엔터테인먼트 장치", "배경화면 정합", "사용자 스캔", "영상 합성"]$patent_keywords_9$::jsonb),
        (10, $patent_keywords_10$["체형 관리", "3D 아바타", "신체 치수", "목표 아바타", "체형 변화 추적"]$patent_keywords_10$::jsonb),
        (11, $patent_keywords_11$["디지털 홈쇼핑", "아바타 영상", "방송 아이템", "3D 상품 데이터", "착용 시뮬레이션"]$patent_keywords_11$::jsonb),
        (12, $patent_keywords_12$["생체정보 인증", "사용자 인증", "전자금융거래", "비밀키 획득", "전자결제 서명"]$patent_keywords_12$::jsonb),
        (13, $patent_keywords_13$["OTP 인증", "다중 등록", "전자금융거래", "인증장치 관리", "보안 인증"]$patent_keywords_13$::jsonb),
        (14, $patent_keywords_14$["내비게이션 고속모드", "고속도로 안내", "IC·JC 출구", "휴게소 정보", "차량 위치"]$patent_keywords_14$::jsonb),
        (15, $patent_keywords_15$["필기 메시지", "이동통신단말", "터치스크린 입력", "멀티미디어 메시지", "필기 이미지"]$patent_keywords_15$::jsonb),
        (16, $patent_keywords_16$["차량 내비게이션", "지도 심벌", "주행 경로", "주변 정보", "시각 인지"]$patent_keywords_16$::jsonb),
        (17, $patent_keywords_17$["영상 통화", "이미지 콘텐츠", "촬영 영상 합성", "콘텐츠 유형", "모바일 통화"]$patent_keywords_17$::jsonb),
        (18, $patent_keywords_18$["의류 착용 적합성", "의류 비즈니스", "신체 정보", "의복압", "온라인 의류 서비스"]$patent_keywords_18$::jsonb),
        (19, $patent_keywords_19$["열차 통합 운영", "마이크로웨이브 통신", "승강장 영상", "장비 감시", "종합사령실"]$patent_keywords_19$::jsonb),
        (20, $patent_keywords_20$["열차 양방향 통신", "마이크로웨이브", "부가서비스", "열차 운행 정보", "객차 영상"]$patent_keywords_20$::jsonb),
        (21, $patent_keywords_21$["NFC 오디오", "등시성 데이터", "실시간 재생", "비휘발성 메모리", "NFC 카드"]$patent_keywords_21$::jsonb),
        (22, $patent_keywords_22$["USB 저장장치", "멀티 파티션", "파티션 숨김", "파티션 표시", "호스트 명령"]$patent_keywords_22$::jsonb),
        (23, $patent_keywords_23$["프로젝트 생산성", "업무분류체계", "산출물 관리", "개발 생산성", "프로젝트 관리"]$patent_keywords_23$::jsonb),
        (24, $patent_keywords_24$["프로젝트 진척관리", "업무분류체계", "진척율 산출", "가중치 관리", "테스트 진척"]$patent_keywords_24$::jsonb),
        (25, $patent_keywords_25$["휴대 단말", "위치정보 서비스", "지도 데이터", "단말 간 위치 전송", "관리 서버"]$patent_keywords_25$::jsonb),
        (26, $patent_keywords_26$["차량 내비게이션", "혼잡 도로", "주행 안내", "혼잡 영역", "2D·3D 지도"]$patent_keywords_26$::jsonb),
        (27, $patent_keywords_27$["차량 내비게이션", "심볼 정보", "3D 랜드마크", "표출 조건", "사용자 인터페이스"]$patent_keywords_27$::jsonb),
        (28, $patent_keywords_28$["주유소 정보", "차량 내비게이션", "TPEG", "연료 가격", "주변 주유소"]$patent_keywords_28$::jsonb),
        (29, $patent_keywords_29$["열차 제어", "무선 LAN", "자동 열차 운행", "차상 장치", "지상 장치"]$patent_keywords_29$::jsonb),
        (30, $patent_keywords_30$["병렬 처리", "지형모델", "영상 데이터", "단위 영역", "모델 갱신"]$patent_keywords_30$::jsonb),
        (31, $patent_keywords_31$["디지털 표면 모델", "병렬 처리", "레퍼런스 영상", "높이값 산출", "DSM 생성"]$patent_keywords_31$::jsonb),
        (32, $patent_keywords_32$["카메라 자세 추정", "촬영화상", "타이포인트 추출", "자세 보정", "정밀 위치결정"]$patent_keywords_32$::jsonb),
        (33, $patent_keywords_33$["디지털 고도모델", "디지털 표면모델", "마스크 데이터", "구조물 제거", "지형 판정"]$patent_keywords_33$::jsonb),
        (34, $patent_keywords_34$["소셜 네트워크 분석", "SNS 데이터", "사용자 관계", "네트워크 지표", "서비스 분석"]$patent_keywords_34$::jsonb),
        (35, $patent_keywords_35$["SNS 마케팅", "소셜 네트워크", "마케팅 대상", "사용자 영향력", "광고 서비스"]$patent_keywords_35$::jsonb),
        (36, $patent_keywords_36$["시스템 자동 감사", "감사 항목", "자체 감사", "감사 로그", "자동 감사 시스템"]$patent_keywords_36$::jsonb),
        (37, $patent_keywords_37$["비밀키 생성", "전자장치 보안", "구성 소자", "난수 생성", "키 관리"]$patent_keywords_37$::jsonb),
        (38, $patent_keywords_38$["CBAC", "접근 제어", "보안 규칙", "서브젝트 조건", "SAC 규칙"]$patent_keywords_38$::jsonb),
        (39, $patent_keywords_39$["원격 검침", "펌웨어 업데이트", "검침 장치", "원격 제어", "업데이트 관리"]$patent_keywords_39$::jsonb),
        (40, $patent_keywords_40$["데이터 변조", "테스트 데이터", "개인정보 보호", "데이터 마스킹", "보안 처리"]$patent_keywords_40$::jsonb),
        (41, $patent_keywords_41$["유조차 관리", "GPS 위치추적", "해치 감시", "밸브 제어", "운송 안전"]$patent_keywords_41$::jsonb),
        (42, $patent_keywords_42$["보안요소(SE)", "모바일 단말", "네트워크 제어", "사용자 인증", "접근 권한"]$patent_keywords_42$::jsonb),
        (43, $patent_keywords_43$["시설 이용 허가", "사용자 인증", "인증 정보", "출입 제어", "권한 확인"]$patent_keywords_43$::jsonb),
        (44, $patent_keywords_44$["보안요소(SE)", "인증정보 관리", "모바일 단말", "보안 저장", "사용자 인증"]$patent_keywords_44$::jsonb),
        (45, $patent_keywords_45$["무선기기 측위", "위치 추정", "신호 세기", "기준 장치", "위치 정보"]$patent_keywords_45$::jsonb),
        (46, $patent_keywords_46$["증강현실", "콘텐츠 제공", "촬영 영상", "객체 인식", "전자장치"]$patent_keywords_46$::jsonb),
        (47, $patent_keywords_47$["포인터 이동", "그래픽 버튼", "사용자 인터페이스", "제스처 입력", "전자장치"]$patent_keywords_47$::jsonb),
        (48, $patent_keywords_48$["정보 주소 관리", "네트워크 주소", "주소 생성", "주소 갱신", "네트워크 자원"]$patent_keywords_48$::jsonb),
        (49, $patent_keywords_49$["음성인식", "발음 평가", "음성 특징", "학습 피드백", "전자기기"]$patent_keywords_49$::jsonb),
        (50, $patent_keywords_50$["복합 장애 조건", "시스템 장애", "장애 모니터링", "프로세스 정보", "관리자 알림"]$patent_keywords_50$::jsonb),
        (51, $patent_keywords_51$["전자 봉인", "시설물 개폐", "리더 태그", "거리 변화", "개폐 모니터링"]$patent_keywords_51$::jsonb),
        (52, $patent_keywords_52$["전자 봉인", "태그 리더", "봉인 감지", "스위치 제어", "시설 보안"]$patent_keywords_52$::jsonb),
        (53, $patent_keywords_53$["정규 표현식", "작업 스케줄링", "전자기기", "조건 매칭", "작업 실행"]$patent_keywords_53$::jsonb),
        (54, $patent_keywords_54$["에너지 저장장치", "충방전 전력변환", "DC 링크", "정전류 제어", "전력 제어"]$patent_keywords_54$::jsonb),
        (55, $patent_keywords_55$["멀티 인증", "통신채널", "멀티 디바이스", "난수 인증", "보안 인증"]$patent_keywords_55$::jsonb),
        (56, $patent_keywords_56$["GUI 전환", "회전 애니메이션", "애니메이션 갭", "화면 전환", "전자기기"]$patent_keywords_56$::jsonb),
        (57, $patent_keywords_57$["데이터 시트", "GUI 검색", "정렬", "데이터 검색", "전자기기"]$patent_keywords_57$::jsonb),
        (58, $patent_keywords_58$["모바일 보안", "관리 권한", "난수 인증", "암호화", "권한 획득"]$patent_keywords_58$::jsonb),
        (59, $patent_keywords_59$["인지형 소셜 네트워크", "소셜 신뢰 지도", "상호작용 분석", "관계 추천", "사용자 네트워크"]$patent_keywords_59$::jsonb),
        (60, $patent_keywords_60$["신변 보호", "위치 기반 서비스", "시간 기반 조건", "모바일 기기", "보호자 알림"]$patent_keywords_60$::jsonb),
        (61, $patent_keywords_61$["게이트웨이 검색", "무선 검색", "인터넷 연결", "검색어 전달", "네트워크 게이트웨이"]$patent_keywords_61$::jsonb),
        (62, $patent_keywords_62$["분산처리", "카메라 영상", "영상 저장", "위치 정보", "서비스 제어"]$patent_keywords_62$::jsonb),
        (63, $patent_keywords_63$["상품 서비스 커뮤니케이션", "접속자 메시지", "상품 정보", "실시간 소통", "서비스 상담"]$patent_keywords_63$::jsonb),
        (64, $patent_keywords_64$["전력 관리", "소비전력 예측", "부하 제어", "전력 절감", "에너지 관리"]$patent_keywords_64$::jsonb),
        (65, $patent_keywords_65$["라우팅 테이블", "어드레스 범위 통합", "네트워크 장치", "주소 범위", "경로 설정"]$patent_keywords_65$::jsonb),
        (66, $patent_keywords_66$["멀티미디어 콘텐츠", "공간 배치", "모바일 화면", "콘텐츠 배열", "사용자 인터페이스"]$patent_keywords_66$::jsonb),
        (67, $patent_keywords_67$["서버 랙 냉각", "서버실 공조", "냉기 유도", "열기 배출", "냉각 보조"]$patent_keywords_67$::jsonb),
        (68, $patent_keywords_68$["항온항습", "실외기", "냉매 순환", "서버실 냉각", "공조 시스템"]$patent_keywords_68$::jsonb),
        (69, $patent_keywords_69$["인터랙티브 이미지", "전화 연결", "수신자 화면", "모바일 통화", "GUI 제공"]$patent_keywords_69$::jsonb),
        (70, $patent_keywords_70$["전력 관리", "신재생에너지", "에너지 저장", "전력 수요", "에너지 제어"]$patent_keywords_70$::jsonb),
        (71, $patent_keywords_71$["배터리 관리", "계층 구조", "서브 BMS", "통신 부하", "셀 밸런싱"]$patent_keywords_71$::jsonb),
        (72, $patent_keywords_72$["배터리 관리", "브로드캐스팅", "시분할 통신", "마스터 슬레이브", "배터리 데이터"]$patent_keywords_72$::jsonb),
        (73, $patent_keywords_73$["배터리 관리", "단일 보드", "마스터부", "슬레이브부", "셀 밸런싱"]$patent_keywords_73$::jsonb),
        (74, $patent_keywords_74$["산업단지 클라우드", "클라우드 서비스", "참조 모델", "분석 DB", "서비스 서버"]$patent_keywords_74$::jsonb),
        (75, $patent_keywords_75$["배터리 관리", "배터리 플로우", "충방전 제어", "상태 모니터링", "에너지 저장"]$patent_keywords_75$::jsonb),
        (76, $patent_keywords_76$["절연 저항", "배터리 측정", "누설 전류", "안전 진단", "측정 장치"]$patent_keywords_76$::jsonb),
        (77, $patent_keywords_77$["메시지 서비스", "신뢰성 보장", "메시지 재전송", "전송 상태", "메시지 큐"]$patent_keywords_77$::jsonb),
        (78, $patent_keywords_78$["하이브리드 모바일 게임", "온라인 오프라인", "게임 모드", "모바일 앱", "서비스 연동"]$patent_keywords_78$::jsonb),
        (79, $patent_keywords_79$["워터마킹", "이미지 워터마크", "이미지 삽입", "저작권 보호", "디지털 콘텐츠"]$patent_keywords_79$::jsonb),
        (80, $patent_keywords_80$["직무발명", "지적 자산화", "신고 관리", "사내 지식", "발명 보상"]$patent_keywords_80$::jsonb),
        (81, $patent_keywords_81$["모바일 기기", "미사용 시간", "사용자 모니터링", "이상 상태 감지", "보호 알림"]$patent_keywords_81$::jsonb),
        (82, $patent_keywords_82$["배송 계획", "도로 상황", "과거 이동 정보", "최적 경로", "배송지 수정"]$patent_keywords_82$::jsonb),
        (83, $patent_keywords_83$["복합 상황 판단", "이벤트 시간 흐름", "장비 이벤트", "상황 규칙", "이벤트 감지"]$patent_keywords_83$::jsonb),
        (84, $patent_keywords_84$["모바일 비콘", "위치 추적", "위치 산출", "경로 파악", "애플리케이션"]$patent_keywords_84$::jsonb),
        (85, $patent_keywords_85$["모바일 원격제어", "온라인 교육", "온라인 회의", "화면 공유", "영상 협업"]$patent_keywords_85$::jsonb),
        (86, $patent_keywords_86$["모바일 단말 판매", "원격 체험", "단말 원격제어", "구매 요청", "온라인 판매"]$patent_keywords_86$::jsonb),
        (87, $patent_keywords_87$["로밍 서비스 테스트", "모바일 원격제어", "통신사 테스트", "이벤트 테스트", "단말 조작"]$patent_keywords_87$::jsonb),
        (88, $patent_keywords_88$["엔터프라이즈 모니터링", "서비스 레벨", "통합 모니터링", "업무 서비스", "리소스 상태"]$patent_keywords_88$::jsonb),
        (89, $patent_keywords_89$["임계값 자동 설정", "시스템 모니터링", "정상값 학습", "장애 감지", "모니터링 시스템"]$patent_keywords_89$::jsonb),
        (90, $patent_keywords_90$["온라인 고객 상담", "모바일 원격제어", "상담 지원", "화면 공유", "고객 응대"]$patent_keywords_90$::jsonb),
        (91, $patent_keywords_91$["얼굴 인식", "얼굴 모션 패턴", "개인 인증", "생체 인증", "위조 방지"]$patent_keywords_91$::jsonb),
        (92, $patent_keywords_92$["증강현실 HMD", "독서 보조", "학습 보조", "시선 추적", "콘텐츠 표시"]$patent_keywords_92$::jsonb),
        (93, $patent_keywords_93$["IT 서비스 건전성", "자동 진단", "운영 지표", "구조 개선", "서비스 분석"]$patent_keywords_93$::jsonb),
        (94, $patent_keywords_94$["공수 추정", "IT 구축 사업", "작업 범위", "추정 모델", "사업 관리"]$patent_keywords_94$::jsonb),
        (95, $patent_keywords_95$["이동통신 데이터", "마케팅 지원", "고객 정보", "제휴사", "요금 할인"]$patent_keywords_95$::jsonb),
        (96, $patent_keywords_96$["온라인 신분증 확인", "안면 인증", "음성 인증", "생체정보 등록", "본인 확인"]$patent_keywords_96$::jsonb),
        (97, $patent_keywords_97$["리스크 관리", "IT 구축 사업", "정량화", "불확실성", "위험 평가"]$patent_keywords_97$::jsonb),
        (98, $patent_keywords_98$["AB 테스팅", "서비스 노출율", "실험군 관리", "사용자 반응", "서비스 최적화"]$patent_keywords_98$::jsonb),
        (99, $patent_keywords_99$["목소리 특징", "본인 인증", "인증 대행", "음성 등록", "해킹 방지"]$patent_keywords_99$::jsonb),
        (100, $patent_keywords_100$["웹 브라우저", "그리드 렌더링", "셀 독립 렌더링", "스크롤 바", "대용량 데이터"]$patent_keywords_100$::jsonb),
        (101, $patent_keywords_101$["계측-수율 상관성", "수율 예측", "계측 데이터", "예측 함수", "반도체 공정"]$patent_keywords_101$::jsonb),
        (102, $patent_keywords_102$["공정/장비 계측 데이터", "미세 변동 감지", "통계 분포", "신뢰구간", "품질 관리"]$patent_keywords_102$::jsonb),
        (103, $patent_keywords_103$["반도체 결함 시각화", "결함 위치", "분포 패턴", "다중 임계값", "결함 이미지"]$patent_keywords_103$::jsonb),
        (104, $patent_keywords_104$["가상 반도체 제조물", "반도체 제조 데이터", "가상 복제", "결함 검사", "수율 예측"]$patent_keywords_104$::jsonb),
        (105, $patent_keywords_105$["장비신뢰지수", "Lot 리스크 스코어", "동적 계측", "반도체 제조", "계측 제어"]$patent_keywords_105$::jsonb),
        (106, $patent_keywords_106$["블록체인 one ID", "인증 지원 서버", "SP 서버", "통합 로그인", "사이트 매핑"]$patent_keywords_106$::jsonb),
        (107, $patent_keywords_107$["IoT 앱 테스트", "모바일 원격제어", "외부 단말 조작", "테스트 자동화", "결과 화면"]$patent_keywords_107$::jsonb),
        (108, $patent_keywords_108$["스마트 팩토리 레이아웃", "자동 설계", "블록 생성", "라인 생성", "배치 알고리즘"]$patent_keywords_108$::jsonb),
        (109, $patent_keywords_109$["레이아웃 효율성", "스마트 팩토리", "효율 지표", "객관 평가", "배치 평가"]$patent_keywords_109$::jsonb),
        (110, $patent_keywords_110$["프로그램 다운로드", "사용자 ID", "로그인 일자", "설치 계획", "동시 설치"]$patent_keywords_110$::jsonb),
        (111, $patent_keywords_111$["가스 감지기", "센서 검정", "센서값 측정", "보정 기준", "감지 정확도"]$patent_keywords_111$::jsonb),
        (112, $patent_keywords_112$["정보 검색", "키워드 관계 정보", "검색 질의", "관계 기반 검색", "검색 결과"]$patent_keywords_112$::jsonb),
        (113, $patent_keywords_113$["설명 가능한 인공지능", "모델링", "시뮬레이션", "이미지 변환", "워크플로우 모델"]$patent_keywords_113$::jsonb),
        (114, $patent_keywords_114$["대화형 홈쇼핑", "인공지능 전화 주문", "STT 음성인식", "상담 자동화", "주문 처리"]$patent_keywords_114$::jsonb),
        (115, $patent_keywords_115$["블록체인 상품권", "코인 기반 결제", "상품권 발행", "거래 관리", "블록체인 서비스"]$patent_keywords_115$::jsonb),
        (116, $patent_keywords_116$["데이터 수집 전송", "함체 패키지", "센서 수집", "통신 모듈", "안테나"]$patent_keywords_116$::jsonb),
        (117, $patent_keywords_117$["AR 비계 검증", "증강현실", "건설 현장", "클라우드 검증", "비계 안전"]$patent_keywords_117$::jsonb),
        (118, $patent_keywords_118$["안전관리", "이미지 학습 모델", "산업 현장", "객체 탐지", "안전보건환경"]$patent_keywords_118$::jsonb),
        (119, $patent_keywords_119$["문서 요약", "딥러닝", "전처리", "유사 문서", "요약 생성"]$patent_keywords_119$::jsonb),
        (120, $patent_keywords_120$["블록체인 스마트 계약", "사용자 키 관리", "콘텐츠 키", "투명성", "키 보안"]$patent_keywords_120$::jsonb),
        (121, $patent_keywords_121$["블록체인 콘텐츠 거래", "콘텐츠 암호키", "디지털 콘텐츠", "전자서명", "거래 검증"]$patent_keywords_121$::jsonb),
        (122, $patent_keywords_122$["모바일 서비스 관제", "원격제어 기술", "대시보드", "이상징후", "iOS·Android"]$patent_keywords_122$::jsonb),
        (123, $patent_keywords_123$["질병 인자 추출", "문서 데이터", "관계 추출", "지식 그래프", "질병·유전자"]$patent_keywords_123$::jsonb),
        (124, $patent_keywords_124$["가명정보 유통", "블록체인", "수익분배", "데이터 거래", "역추적"]$patent_keywords_124$::jsonb),
        (125, $patent_keywords_125$["챗봇 시나리오", "자연어 처리 엔진", "인텐트", "엔티티", "답변 생성"]$patent_keywords_125$::jsonb),
        (126, $patent_keywords_126$["한글 숫자 표현", "숫자 추출", "토큰화", "품사 판별", "자연어 처리"]$patent_keywords_126$::jsonb),
        (127, $patent_keywords_127$["AI 모델 서빙", "모델 등록", "모델 배포", "모델 검색", "서빙 인프라"]$patent_keywords_127$::jsonb),
        (128, $patent_keywords_128$["오디오북 제작", "보이스 스타일 분석", "품질 자동 검수", "참여자 메타정보", "낭독 품질"]$patent_keywords_128$::jsonb),
        (129, $patent_keywords_129$["AI 모델 운영", "단일 엔드포인트", "API 관리", "모델 라우팅", "포드 운영"]$patent_keywords_129$::jsonb),
        (130, $patent_keywords_130$["모델 서버 스케일링", "AI 모델 운영", "포드 관리", "부하 대응", "서빙 확장"]$patent_keywords_130$::jsonb),
        (131, $patent_keywords_131$["이동식 3D 마커", "증강현실 정합", "현장 검측", "촬영모듈", "표시모듈"]$patent_keywords_131$::jsonb),
        (132, $patent_keywords_132$["이동경로 분석", "통신데이터 추출", "위치 데이터", "이동 패턴", "정보추출"]$patent_keywords_132$::jsonb),
        (133, $patent_keywords_133$["태양광 발전", "수소연료전지", "하이브리드 발전", "발전 제어", "시뮬레이션"]$patent_keywords_133$::jsonb),
        (134, $patent_keywords_134$["주식 시장 예측", "비정형 데이터", "뉴스 분석", "가중치 산출", "예측 모델"]$patent_keywords_134$::jsonb),
        (135, $patent_keywords_135$["금융시장 예측", "예측 근거", "인공지능 모델", "시각화", "설명 가능성"]$patent_keywords_135$::jsonb),
        (136, $patent_keywords_136$["시장 이벤트 추출", "경제 뉴스", "주가 지수", "이벤트 분석", "예측 설명"]$patent_keywords_136$::jsonb),
        (137, $patent_keywords_137$["금융시장 예측정보", "인공지능 모델", "예측 시각화", "투자 지표", "시장 분석"]$patent_keywords_137$::jsonb),
        (138, $patent_keywords_138$["금융시장 데이터", "이상치 제거", "데이터 복원", "이벤트 정보", "예측 정확도"]$patent_keywords_138$::jsonb),
        (139, $patent_keywords_139$["금융시장 데이터 예측", "인공지능 모델", "학습 데이터", "예측 분석", "시장 지표"]$patent_keywords_139$::jsonb),
        (140, $patent_keywords_140$["네트워크 이중화", "전자 패치", "통신 모듈", "제어 모듈", "장애 대응"]$patent_keywords_140$::jsonb),
        (141, $patent_keywords_141$["ESG 경영관리", "플랫폼 운영", "ESG 지표", "가중치 평가", "경영 성과"]$patent_keywords_141$::jsonb),
        (142, $patent_keywords_142$["반도체 소재", "후보물질", "물성예측", "무기 물질", "소재 개발"]$patent_keywords_142$::jsonb),
        (143, $patent_keywords_143$["문서 양식 변환", "웹폼 생성", "업무 절차", "워크플로우", "문서 자동화"]$patent_keywords_143$::jsonb),
        (144, $patent_keywords_144$["웹 문서 생성", "드래그 앤 드롭", "데이터 추출", "웹 편집", "문서 편집"]$patent_keywords_144$::jsonb),
        (145, $patent_keywords_145$["업무 프로세스", "웹 문서 매칭", "워크플로우 관리", "맞춤형 프로세스", "작업 절차"]$patent_keywords_145$::jsonb),
        (146, $patent_keywords_146$["문서 이미지", "양식 추출", "위치 식별", "크기 식별", "웹 문서 변환"]$patent_keywords_146$::jsonb),
        (147, $patent_keywords_147$["오디오북 오류 검출", "STT 엔진", "NLP", "낭독 오류", "자동 검수"]$patent_keywords_147$::jsonb),
        (148, $patent_keywords_148$["안전 점수", "근로자 정보", "블록체인 이력", "자격증 관리", "건강검진"]$patent_keywords_148$::jsonb),
        (149, $patent_keywords_149$["근로자 구인공고", "안전 점수", "블록체인 이력", "자격증 검증", "근무 평가"]$patent_keywords_149$::jsonb),
        (150, $patent_keywords_150$["위험성 평가 회의", "작업 허가", "안전관리", "작업 현장", "절차 관리"]$patent_keywords_150$::jsonb),
        (151, $patent_keywords_151$["안전점검", "현장 근로자 참여", "시정조치", "점검 결과", "안전관리"]$patent_keywords_151$::jsonb),
        (152, $patent_keywords_152$["작업 현장", "구조 요청", "SOS 알람", "대피 안내", "사고 이벤트"]$patent_keywords_152$::jsonb),
        (153, $patent_keywords_153$["NF3 가스", "정비 자동화", "CELL Body", "다관절 로봇", "무인반송차량"]$patent_keywords_153$::jsonb),
        (154, $patent_keywords_154$["NF3 가스", "이물질 제거", "CELL Body 세척", "자동문 제어", "니켈 배출"]$patent_keywords_154$::jsonb),
        (155, $patent_keywords_155$["독성 물질 운송", "무인반송차량", "NF3 생산시설", "전용 용기", "진동 측정"]$patent_keywords_155$::jsonb),
        (156, $patent_keywords_156$["메시지 지향 미들웨어", "토폴로지 모니터링", "병목 구간", "트랜잭션 정보", "시스템 상태"]$patent_keywords_156$::jsonb),
        (157, $patent_keywords_157$["메시지 지향 미들웨어", "전송 실패 메시지", "이력 추적", "사후 재전송", "메시지 라우팅"]$patent_keywords_157$::jsonb),
        (158, $patent_keywords_158$["블록체인 서비스", "스마트 컨트랙트", "Deploy Manager", "컨트랙트 배포", "트랜잭션 처리"]$patent_keywords_158$::jsonb),
        (159, $patent_keywords_159$["설비 제어 프로그램", "시나리오 배포", "EAP 서비스", "배포 관리", "서비스 단위"]$patent_keywords_159$::jsonb),
        (160, $patent_keywords_160$["설비 제어 프로그램", "캐시 메모리", "메시지 처리", "EAP", "처리 규칙"]$patent_keywords_160$::jsonb),
        (161, $patent_keywords_161$["반려동물 사진 분류", "이미지 태깅", "펫 케어 예약", "보호자 정보", "객체 감지"]$patent_keywords_161$::jsonb),
        (162, $patent_keywords_162$["CMP Pad", "레이저 마킹", "스테이지부", "집진 유닛", "제품 식별"]$patent_keywords_162$::jsonb),
        (163, $patent_keywords_163$["CMP Pad", "자동 건조", "웨이퍼 카세트", "AGV 이송", "건조 설비"]$patent_keywords_163$::jsonb),
        (164, $patent_keywords_164$["CMP Pad", "자동 적재", "시편 커팅", "에이징", "무인반송차량"]$patent_keywords_164$::jsonb),
        (165, $patent_keywords_165$["CMP Pad", "물류 관리", "RTD", "MCS", "이송 경로"]$patent_keywords_165$::jsonb),
        (166, $patent_keywords_166$["무인운반차", "얼라인 시스템", "변위 센서", "QR 코드", "비전 카메라"]$patent_keywords_166$::jsonb),
        (167, $patent_keywords_167$["블록체인 합의", "서명 검증", "밸리데이터 노드", "트랜잭션", "검증 요청"]$patent_keywords_167$::jsonb),
        (168, $patent_keywords_168$["자산배분", "강화학습", "액터-크리틱", "상품 트렌드", "투자 전략"]$patent_keywords_168$::jsonb),
        (169, $patent_keywords_169$["가상 반도체 제품", "반도체 제조 데이터", "실시간 복제", "결함 검출", "수율 예측"]$patent_keywords_169$::jsonb),
        (170, $patent_keywords_170$["사진 액자 내비게이션", "주행 안내", "조합 모드", "이미지 표시", "지도 데이터"]$patent_keywords_170$::jsonb),
        (171, $patent_keywords_171$["복합 상황 결정", "사건 시간 흐름", "장치 이벤트", "상황 규칙", "사건 감지"]$patent_keywords_171$::jsonb),
        (172, $patent_keywords_172$["가상 반도체 제품", "제조 데이터", "실시간 복제", "가상 검사", "결함 검출"]$patent_keywords_172$::jsonb),
        (173, $patent_keywords_173$["미세 변화 감지", "공정 계측 데이터", "통계 분포", "목표 범위", "품질 관리"]$patent_keywords_173$::jsonb),
        (174, $patent_keywords_174$["반도체 수율 예측", "머신러닝", "신경망 모델", "데이터 유형 분류", "제조 공정"]$patent_keywords_174$::jsonb),
        (175, $patent_keywords_175$["장비 신뢰성 지수", "동적 로트 측정", "위험 점수", "반도체 품질관리", "측정 여부"]$patent_keywords_175$::jsonb),
        (176, $patent_keywords_176$["블록체인 원아이디", "인증 지원 서버", "SP 서버", "사이트 매핑", "통합 로그인"]$patent_keywords_176$::jsonb),
        (177, $patent_keywords_177$["질병 인자 연관성", "문서 데이터", "관계 추출", "지식 그래프", "유전자·단백질"]$patent_keywords_177$::jsonb),
        (178, $patent_keywords_178$["상자 기능 내비게이션", "주행 안내", "상자 이미지", "조합 모드", "지도 데이터"]$patent_keywords_178$::jsonb),
        (179, $patent_keywords_179$["미세 변화 감지", "공정/장비 데이터", "통계 분포", "목표 범위", "품질 모니터링"]$patent_keywords_179$::jsonb),
        (180, $patent_keywords_180$["측정 제어", "장비 신뢰성 지수", "위험 점수", "반도체 제조", "측정 여부"]$patent_keywords_180$::jsonb),
        (181, $patent_keywords_181$["설명 가능한 AI", "모델링", "시뮬레이션", "워크플로우 모델", "이미지 변환"]$patent_keywords_181$::jsonb),
        (182, $patent_keywords_182$["장비 신뢰 지수", "로트 위험 점수", "동적 계측 제어", "FDC 인터록", "반도체 제조"]$patent_keywords_182$::jsonb),
        (183, $patent_keywords_183$["계측 데이터 변동", "미세 변동 검지", "통계 분포", "신뢰구간", "제조 공정"]$patent_keywords_183$::jsonb),
        (184, $patent_keywords_184$["질병 인자 연관성", "문서 데이터", "인공신경망", "관계 추출", "지식 그래프"]$patent_keywords_184$::jsonb),
        (185, $patent_keywords_185$["교차로 안내", "내비게이션", "주행 경로", "남은 교차로 수", "회전 기호"]$patent_keywords_185$::jsonb)
)
update patents
set keywords = patent_keyword_updates.keywords
from patent_keyword_updates
where patents.id = patent_keyword_updates.id;

commit;
