create table pre_evaluations (
    id bigint generated by default as identity,
    user_id bigint not null,
    title varchar(200) not null,
    technical_description text not null,
    claims text not null,
    related_business varchar(500),
    target_countries varchar(500),
    status varchar(20) not null,
    report_url varchar(1000),
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_pre_evaluations primary key (id),
    constraint fk_pre_evaluations_user foreign key (user_id) references users (id)
);

create table pre_evaluation_chat_messages (
    id bigint generated by default as identity,
    pre_evaluation_id bigint not null,
    role varchar(20) not null,
    content text not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_pre_evaluation_chat_messages primary key (id),
    constraint fk_pre_evaluation_chat_messages_pre_evaluation
        foreign key (pre_evaluation_id) references pre_evaluations (id) on delete cascade
);

create index idx_pre_evaluations_user_id on pre_evaluations (user_id);
create index idx_pre_evaluation_chat_messages_pre_evaluation_id
    on pre_evaluation_chat_messages (pre_evaluation_id);
