create table departments (
    id bigint generated by default as identity,
    name varchar(100) not null,
    status varchar(20) not null default 'ACTIVE',
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_departments primary key (id),
    constraint uk_departments_name unique (name)
);

create table users (
    id bigint generated by default as identity,
    login_id varchar(50) not null,
    name varchar(100) not null,
    email varchar(200) not null,
    password varchar(200) not null,
    role varchar(20) not null,
    department_id bigint,
    status varchar(20) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_users primary key (id),
    constraint uk_users_login_id unique (login_id),
    constraint uk_users_email unique (email),
    constraint fk_users_department foreign key (department_id) references departments (id)
);

create table patents (
    id bigint generated by default as identity,
    title varchar(500) not null,
    application_number varchar(20) not null,
    registration_number varchar(20),
    publication_number varchar(20),
    announcement_number varchar(20),
    application_date date,
    registration_date date,
    publication_date date,
    announcement_date date,
    ipc_code varchar(200),
    cpc_code varchar(200),
    applicant varchar(200),
    inventor varchar(500),
    expiry_date date,
    citation_count integer,
    original_pdf_key varchar(500),
    management_number varchar(50),
    business_field varchar(200),
    tech_field varchar(200),
    related_products varchar(255),
    filing_country varchar(100),
    is_joint_application boolean,
    joint_applicant varchar(200),
    initial_department varchar(200),
    current_department_id bigint,
    keywords varchar(255),
    overview text,
    core_content text,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_patents primary key (id),
    constraint uk_patents_application_number unique (application_number),
    constraint fk_patents_current_department foreign key (current_department_id) references departments (id)
);

create table patent_annuities (
    id bigint generated by default as identity,
    patent_id bigint not null,
    annuity_year integer not null,
    due_date date,
    paid_date date,
    status varchar(20) not null,
    amount integer,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_patent_annuities primary key (id),
    constraint fk_patent_annuities_patent foreign key (patent_id) references patents (id)
);

create table patent_legal_status (
    id bigint generated by default as identity,
    patent_id bigint not null,
    status varchar(20) not null,
    changed_at date,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_patent_legal_status primary key (id),
    constraint fk_patent_legal_status_patent foreign key (patent_id) references patents (id)
);

create table review_cycles (
    id bigint generated by default as identity,
    name varchar(100) not null,
    type varchar(20) not null,
    start_date date not null,
    end_date date not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_review_cycles primary key (id),
    constraint uk_review_cycles_name unique (name)
);

create table reports (
    id bigint generated by default as identity,
    patent_id bigint not null,
    report_key varchar(500),
    status varchar(20) not null,
    evaluated_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_reports primary key (id),
    constraint fk_reports_patent foreign key (patent_id) references patents (id)
);

create table reviews (
    id bigint generated by default as identity,
    patent_id bigint not null,
    department_id bigint not null,
    review_cycle_id bigint not null,
    report_id bigint,
    opinion varchar(20),
    comment text,
    status varchar(20) not null,
    submitted_at timestamp(6) with time zone,
    due_date date not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_reviews primary key (id),
    constraint uk_reviews_cycle_patent_department unique (review_cycle_id, patent_id, department_id),
    constraint fk_reviews_patent foreign key (patent_id) references patents (id),
    constraint fk_reviews_department foreign key (department_id) references departments (id),
    constraint fk_reviews_review_cycle foreign key (review_cycle_id) references review_cycles (id),
    constraint fk_reviews_report foreign key (report_id) references reports (id)
);

create index idx_users_department_id on users (department_id);
create index idx_patents_current_department_id on patents (current_department_id);
create index idx_patent_annuities_patent_id on patent_annuities (patent_id);
create index idx_patent_legal_status_patent_id on patent_legal_status (patent_id);
create index idx_reviews_patent_id on reviews (patent_id);
create index idx_reviews_department_id on reviews (department_id);
create index idx_reviews_review_cycle_id on reviews (review_cycle_id);
create index idx_reviews_report_id on reviews (report_id);
create index idx_reports_patent_id on reports (patent_id);
