create table departments (
    id bigint generated by default as identity,
    name varchar(100) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_departments primary key (id),
    constraint uk_departments_name unique (name)
);

create table users (
    id bigint generated by default as identity,
    login_id varchar(50) not null,
    name varchar(100) not null,
    email varchar(200) not null,
    password varchar(200) not null,
    role varchar(20) not null,
    department_id bigint,
    status varchar(20) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_users primary key (id),
    constraint uk_users_login_id unique (login_id),
    constraint uk_users_email unique (email),
    constraint fk_users_department foreign key (department_id) references departments (id)
);

create table patents (
    id bigint generated by default as identity,
    title varchar(500) not null,
    application_number varchar(20) not null,
    registration_number varchar(20),
    publication_number varchar(20),
    announcement_number varchar(20),
    application_date date,
    registration_date date,
    publication_date date,
    announcement_date date,
    ipc_code varchar(200),
    cpc_code varchar(200),
    applicant varchar(200),
    inventor varchar(500),
    expiry_date date,
    citation_count integer,
    original_pdf_key varchar(500),
    management_number varchar(50),
    business_field varchar(200),
    tech_field varchar(200),
    related_products varchar(255),
    filing_country varchar(100),
    is_joint_application boolean,
    joint_applicant varchar(200),
    initial_department varchar(200),
    keywords varchar(255),
    overview text,
    core_content text,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_patents primary key (id),
    constraint uk_patents_application_number unique (application_number)
);

create table patent_departments (
    id bigint generated by default as identity,
    patent_id bigint not null,
    department_id bigint not null,
    assigned_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_patent_departments primary key (id),
    constraint fk_patent_departments_patent foreign key (patent_id) references patents (id),
    constraint fk_patent_departments_department foreign key (department_id) references departments (id)
);

create index idx_users_department_id on users (department_id);
create index idx_patent_departments_patent_id on patent_departments (patent_id);
create index idx_patent_departments_department_id on patent_departments (department_id);
