create table patent_extract_jobs (
    id bigint generated by default as identity,
    object_key varchar(500),
    status varchar(30) not null,
    result_json jsonb,
    error_message text,
    uploaded_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_patent_extract_jobs primary key (id)
);

create index idx_patent_extract_jobs_status on patent_extract_jobs (status);
